services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: backend
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: (7!#dcb+c!ald0s=1&(gt8amhs38&%%k%l0y=4$)^q6zygi8*r
    ports:
      - "8000:8000"
    command: bash -c 'fastapi dev --host 0.0.0.0 --port 8000'
    volumes:
      - ./core:/usr/src/core