"""added age field

Revision ID: b7abee24cb4e
Revises: bc0e26e3d2bf
Create Date: 2025-09-27 13:37:45.081935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7abee24cb4e'
down_revision: Union[str, Sequence[str], None] = 'bc0e26e3d2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('aeg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'aeg')
    # ### end Alembic commands ###
